# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1onOfcfgah7OMznbrbnw_SbuJtZZpGveb
"""

import logging

LOG_FILE = "system.log"

logging.basicConfig(
    filename=LOG_FILE,
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)
# =====================================
# Backup & Recovery System -
# =====================================


import os
import shutil
import csv
import hashlib
from datetime import datetime
from google.colab import files


# Folders

BACKUP_FOLDER = "backups"
HISTORY_FILE = "backup_history.csv"


os.makedirs(BACKUP_FOLDER, exist_ok=True)


# File Hash


def get_hash(file):

    h = hashlib.md5()

    with open(file,"rb") as f:
        h.update(f.read())

    return h.hexdigest()



# Upload File


def upload_file():

    print("Upload your file")

    uploaded = files.upload()

    filename = list(uploaded.keys())[0]

    print("Uploaded:", filename)

    return filename



# Create Backup


def create_backup(file):

    time = datetime.now().strftime(
        "%Y%m%d_%H%M%S"
    )


    backup_name = (
        file + "_" + time
    )


    destination = os.path.join(
        BACKUP_FOLDER,
        backup_name
    )


    shutil.copy(
        file,
        destination
    )


    size = os.path.getsize(destination)



    with open(
        HISTORY_FILE,
        "a",
        newline=""
    ) as f:


        writer = csv.writer(f)


        writer.writerow([

            datetime.now(),

            file,

            destination,

            size,

            "SUCCESS"

        ])



    print("Backup Created")
    print(destination)

    return destination
logging.info(f"Backup created successfully: {file}")




# History

def show_history():


    if not os.path.exists(HISTORY_FILE):

        print("No history")

        return


    with open(HISTORY_FILE) as f:

        reader = csv.reader(f)


        for row in reader:

            print(row)




# Restore


def restore_backup():

    backup = input(
        "Enter backup name: "
    )


    if os.path.exists(backup):

        restore_name = (
            "restored_" +
            os.path.basename(backup)
        )


        shutil.copy(
            backup,
            restore_name
        )


        print(
            "File Restored:",
            restore_name
        )


    else:

        print("Backup not found")


logging.info("File restored successfully")


# Verify


def verify():

    original = input(
        "Original file name: "
    )


    backup = input(
        "Backup file name: "
    )


    if get_hash(original)==get_hash(backup):

        print(
            "Backup Verified"
        )

    else:

        print(
            "Backup Different"
        )


logging.info("Backup verification completed")

# Report


def report():

    count=0


    if os.path.exists(HISTORY_FILE):

        with open(HISTORY_FILE) as f:

            for line in f:

                count+=1



    print(
        "Total Backups:",
        count
    )





# MAIN MENU



backup_path = None


while True:


    print("""

========= BACKUP SYSTEM =========

1. Upload & Create Backup

2. View Backup History

3. Restore Backup

4. Verify Backup

5. Backup Report

6. Exit

""")


    choice=input(
        "Enter choice by number: "
    )



    if choice=="1":

        file = upload_file()

        backup_path=create_backup(file)



    elif choice=="2":

        show_history()



    elif choice=="3":

        restore_backup()



    elif choice=="4":

        verify()



    elif choice=="5":

        report()



    elif choice=="6":

        print("System Closed")

        break


    else:

        print("Invalid Choice")